version: "3"
services:
  db:
    build: importer/data/mongo/
    ports:
      - 57017:27017
  importer:
      build: importer/
      command: bash demo.sh
      network_mode: host
      depends_on:
        - db

