version: "3"
services:
  db:
    build: mongo/
    ports:
      - 27017:57017
  client:
      build: client/
      command: python ./client.py
      network_mode: host
      depends_on:
        - db

